### PR TITLE
Added functions which have not request callbacks

### PR DESCRIPTION
**Pull request by ldrahnik**

### CODE REVIEW

**Comment by Budry** [comment]
Hi,
this can be use useful :+1: but I'm not sure if I understand it. Method `addField()` rewrite value from array/entity and use a new value?

**Comment by ldrahnik** [comment]
You are right, has been changed

**Comment by Budry** [comment]
Thanks!
I think about merging addFiledCallback and addField into one method because addField sounds not good because it adds nothing and is useless have two methods for this. One method can accept value or closure and can have a better name. What do you think about this?

**Comment by ldrahnik** [comment]
Yep, but add exception when is parameter invalid, and keep values in separated list as it is now (don't convert those to callback). Should I do it or you?

**Comment by Budry** [comment]
I do it wait few minutes *(don't close this pull please)*.

How name for this method have you idea? I think that `addFieldResolver()` will be good but if you know better name I can use it.
Method will be accept all data types. For closure method will run argument as callback and for others types change value. It is ok? I don't see reason for exception (or separated list)

**Comment by ldrahnik** [comment]
Ok.

I think addFieldValue(), you can combine it. Yeah, everything what is not callable is value. Exception is not needed and separate lists also.

**Comment by Budry** [comment]
Thanks.
Solved in 6a2b0c24a3e05800f3008becf89f72364f900df6

**Comment by ldrahnik** [comment]
Thanks :)

**Pull request closed without merging**
